### ISSUE TITLE
Securing branches and banning merge commits

### ISSUE THREAD

**Issue by NathaelB** [dev-sys-do/sealci#24]
It has been observed that two merge commits have been introduced on the main branch, which runs counter to the good practices that should be put in place to maintain a clean and linear git history (squash, rebase).

In order to guarantee the quality of the code and make it easier to track changes, I propose to implement the following actions:

1. Securing the main branches
    - Protect the `main` branch to prevent any direct push.
    - Require all modifications to these branches to go through a PR approved by at least one other developer.

2. Prohibit merge commits:
   - Configure a rule on the repository to prohibit merge commits in PRs. Only the ‘Squash and merge’ or ‘Rebase and merge’ options should be allowed to guarantee a linear git history.
   - Make the team aware of the correct use of merge options.

### Rationale
Clean git history: merge commits create additional branches that make it harder to understand the history. Banning these commits will keep the history linear and easier to follow.
Reduced conflicts: A linear history minimises the risk of conflicts during future integrations.
Improved code review: Protecting branches ensures that any changes are reviewed by another member of the team, thereby improving code quality.

Given that you have sufficient rights to carry out this action, here is a proposal for establishing rules on our repo @sameo

**Comment by hugoponthieu** [comment]
Merge commit is no longer possible
