### ISSUE TITLE
Agent registration endpoint

### ISSUE THREAD

**Issue by Razano26** [dev-sys-do/sealci#29]
Add agent url in registration process to store endpoint where sends future action.

So the solution is creating an interface `RegisterAgentRequest` wrapping Health and the url.

[api/proto/scheduler/agent.proto](https://github.com/dev-sys-do/sealci/blob/main/api/proto/scheduler/agent.proto)

**Comment by theotchlx** [comment]
@benoit-planche found a solution, implemented at https://github.com/dev-sys-do/sealci/blob/feat/scheduler/api/proto/scheduler/agent.proto

on our PR:
https://github.com/dev-sys-do/sealci/pull/13

**Comment by hugoponthieu** [comment]
It is ok for me.
