### ISSUE TITLE
Spread repo url

### ISSUE THREAD

**Issue by hugoponthieu** [dev-sys-do/sealci#45]
When the agent launch an action it needs to checkout the repo. 
The goal of this issue is to update proto then the code to spread the repo url.  

As the scheduler and the agent does not implement the pipelines abstraction we need to send the repo url on each action.

## Agent

We need to implement a service that clone the repo in the container then set the workdir of exec to be the cloned repo.

## Scheduler

Update protos.

## Controller 

Implement protos of scheduler.

## Monitor

Send the repo url on each pipeline.

(Don't mind commenting for more precise info)

**Comment by theotchlx** [comment]
(@dev-sys-do/sealci-scheduler Team)
So, you basically need a `string repo_url` in the .proto request sent to the Agent? We can suggest changes to the .proto

**Comment by hugoponthieu** [comment]
Yes and maybe some refactoring if needed.

**Comment by Courtcircuits** [comment]
FYI, we did it : https://github.com/dev-sys-do/sealci/blob/a20455a5748373761ec39c2709e22bfad015fe29/api/proto/scheduler/controller.proto
We added a `repo_url` field to the scheduler.proto and we added to our open api spec a `repo_url` field

**Comment by baptistebronsin** [comment]
As @Courtcircuits said, the Controller needs the repo url. Then we, the Monitor, have updated our api call with this new information : https://github.com/dev-sys-do/sealci/blob/3b602b8c88aaf00a82dd67b38ccb0d2c78eb435e/monitor/src/controller.rs#L21
